### ISSUE TITLE
[ALA] backslash escape 

### ISSUE THREAD

**Issue by denny-lclin** [SigmaHQ/legacy-sigmatools#9]
1.
Sigma Rule: 
```
detection:
    rule1:
        filefullpath|endswith:          
            - '\OvOHRDDL.exe'
    condition: rule1
```
and run `tools/sigmac -t ala my_rule.yml`

Expect:
```
Table | where (filefullpath endswith '\\OvOHRDDL.exe')
```
Actual:
```
Table | where (filefullpath endswith @'\\\\OvOHRDDL.exe')
```
____
2.
Sigma Rule: 
```
detection:
    rule1:
        filefullpath|endswith:          
            - '\\*\OvOHRDDL.exe'
    condition: rule1
```
and run `tools/sigmac -t ala my_rule.yml`
Expect:
```
Table | where (filefullpath matches regex @'(?i).*\\.*\\OvOHRDDL.exe')
```
Actual:
```
Table | where (filefullpath matches regex @'(?i).*\\\\\\.*\\\\OvOHRDDL.exe')
```
